predicates:
  - name: "u_p1"
    types: ["robot"]
    ae_generator:
      name: "exhaustive"
      kwargs:
        search_region: [1, 1, 1, 1]
        ae_var_ids: [0]
    nn_archi: 
      type: "MLP"
      input_dim: 10
      layer_size: 128
      initializer: "xavier"
    optimizer:
      type: "AdamW"
      kwargs:
        lr: 0.001
    lr_scheduler:
      type: "StepLR"
      kwargs:
        step_size: 40
        gamma: 0.1
    batch_size: 64
    num_epochs: 100
    val_loss_thresh: 0.05
    cls_threshold: 0.5
    val_freq: 10

  - name: "u_p2"
    types: ["block"]
    ae_generator:
      name: "exhaustive"
      kwargs:
        search_region: [1, 1, 1, 1]
        ae_var_ids: [0]
    nn_archi: 
      type: "MLP"
      input_dim: 10
      layer_size: 128
      initializer: "xavier"
    optimizer:
      type: "AdamW"
      kwargs:
        lr: 0.001
    lr_scheduler:
      type: "StepLR"
      kwargs:
        step_size: 40
        gamma: 0.1
    batch_size: 64
    num_epochs: 100
    val_loss_thresh: 0.05
    cls_threshold: 0.5
    val_freq: 10

  - name: "b_p1"
    types: ["robot", "block"]
    ae_generator:
      name: "exhaustive"
      kwargs:
        search_region: [1, 1, 1, 1]
        ae_var_ids: [0]
    nn_archi: 
      type: "MLP"
      input_dim: 10
      layer_size: 128
      initializer: "xavier"
    optimizer:
      type: "AdamW"
      kwargs:
        lr: 0.001
    lr_scheduler:
      type: "StepLR"
      kwargs:
        step_size: 40
        gamma: 0.1
    batch_size: 64
    num_epochs: 100
    cls_threshold: 0.5
    val_loss_thresh: 0.05
    val_freq: 10